spring:
  profiles.active: dev
  application:
    name: demo

jwt.secret: thisIsMySecretPassword

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    com.dci.demo: DEBUG
  file:
    name: logs/demo.log