spring:
  profiles.active: dev
  application:
    name: demo
  h2.console.enabled: true
  h2.console.path: /h2-console
  jpa:
    properties.hibernate.generate_statistics: true
    show-sql: true
    properties.hibernate.format_sql: true
  logging.level.org.hibernate.stat: debug
  datasource.url: jdbc:h2:mem:testdb
  datasource.username: sa
  datasource.password: password
  data.jpa.repositories.bootstrap-mode: default

logging.level.org.hibernate.type: trace

jwt.secret: thisIsMySecretPassword

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    com.dci.demo: DEBUG
  file:
    name: logs/demo.log