DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id IDENTITY NOT NULL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS images;
CREATE TABLE images (
    id IDENTITY NOT NULL PRIMARY KEY,
    fileName VARCHAR(100) NOT NULL UNIQUE,
    contentType VARCHAR(256) NOT NULL,
    contents BLOB NOT NULL
);